# Site settings
title: Inform/Transform
email: hello@informtransform.info
url: https://zararah.github.io/informtransform.info
description: "Inform/Transform is a zine about the different ways that information can be controlled, manipulated and transformed, highlighted through historical examples and drawings."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
