# Site settings
title: Inform/Transform
email: hello@informtransform.info
url: https://inform-transform.github.io
description: "Inform/Transform is a zine about the different ways that information can be controlled, manipulated and transformed."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
